name: flutter_bottom_navigation_with_nested_routing_tutorial
description: Flutter Bottom Navigation with Nested Routing Tutorial.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^2.3.2
  salomon_bottom_bar: ^3.1.0

  loggy: ^2.0.1
  get: ^4.6.5

  # For database and state management
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  prompt_dialog: ^1.0.0
  firebase_database: ^9.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  auto_route_generator: ^2.3.2
  build_runner: ^2.1.2
flutter:
  uses-material-design: true